name: Update App

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  update-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: go mod download
      - name: Update app
        run: ./update.sh
